run:
  timeout: 5m
  modules-download-mode: readonly
  issues:
    exclude-dirs:
      - vendor
      - bin
    max-issues-per-linter: 0
    max-same-issues: 0
    exclude-rules:
      - path: _test\.go
        linters:
          - gocyclo
          - dupl
          - gosec
    exclude:
      - "should have a package comment"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - bodyclose
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 2
  misspell:
    locale: US

