version: '3.8'
services:
 app:
   build: .
   ports:
     - "8080:8080"
   environment:
     - APP_ENV=production
     - APP_PORT=8080
     - MONITORING_ENABLED=true
     - METRICS_PREFIX=app_prod
   healthcheck:
     test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
     interval: 30s
     timeout: 10s
     retries: 3


