version: '3.8'

services:
  mvp-api:
    build:
      context: .
      dockerfile: cmd/mvp-api/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - APP_ENV=production
      - APP_PORT=3003
      - APP_HOST=0.0.0.0
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3003/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
